### ISSUE TITLE
shmget: fonction not implemented

### ISSUE THREAD

**Issue by yougz11** [sharyer/GSMEvil#3]
Hi,
I m facing this problem when i launch kal -s GSM900 :

shmget: Fonction not implemented
terminate called after throwing an instance of 'std::runtime_error' what(): circular_buffer: shmget
zsh: abort           kal -s GSM900

I'm under nethunter, everything is well installed so i really don't understand

**Comment by ninjhacks** [comment]
kal is not my tool if you have any issue related to kal then I suggest to ask on kal repository.
